#!/bin/bash

# monitors the diskspace for each vmail adress

TMPFILE="/tmp/mailadresssize.tmp"

# if your virtual mailaccounts stored under /var/vmail then you can leave this unmodified
find /var/vmail/* -mindepth 1 -maxdepth 1 -exec du -sc {} \; | grep -v total | awk '{print $2 "/"$1}' | sort | awk 'BEGIN {FS="/"} {print $5" "$4" "$6}' | sed 's/\./_/g' > $TMPFILE

if [ "$1" = "autoconf" ]; then
        echo yes 
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title maildirs by size (ver.2014-11-11)'
        echo 'graph_args --base 1024 -l 0 '
        echo 'graph_scale yes'          # we want human readable sizes like KB and MB
        echo 'graph_vlabel maildirsize in bytes'
        echo 'graph_category postfix'

        while read linelabels
        do
                # printf doesnt output newline so we use this to get nice mail labels with @ and . 
                echo ${linelabels} | awk '{printf $1"AT"$2".label "}'           # data source name:     mailATaddress_com
                echo ${linelabels} | awk '{print  $1"@"$2}' | sed 's/_/\./g'    # date source label:    mail@address.com
        done < $TMPFILE
        exit 0
fi

while read linelabels
do
                echo ${linelabels} | awk '{print $1"AT"$2".value "$3}'
done < $TMPFILE

rm $TMPFILE
