#!/usr/local/bin/bash
#
# Plugin to monitor deduplication ratio on zfs pools 
#
# Parameters:
#
#       config   (required)
#
# Magic markers (optional - only used by munin-config and some
# installation scripts):


if [ "$1" = "config" ]
then
    echo 'graph_args -l 0 --vertical-label deduplication rate'
    echo 'graph_title ZFS pools deduplication rate'
    echo 'graph_category zfs'
    echo 'graph_info This graph shows the deduplication rate of every zpool.'

    ((n=0))
    for i in `zpool list | egrep -v "^NAME" | awk '{print $1}'`;
    do
        ((n++))
        echo "pool$n.label "$i;
    done
    exit 0
fi

((n=0))
for i in `zpool list | egrep -v "^NAME" | awk '{print $6}' | awk 'BEGIN {FS="x"} {print $1}'`;
do
    ((n++))
    echo "pool$n.value "$i;
done

